# **Marketing Exercise**

Welcome to a quick exercise for you to practice your pandas skills! We will be using a [Marketing Dataset](https://www.kaggle.com/rodsaldanha/arketing-campaign) from Kaggle, but we made some changes to the dataset to showcase some particular examples more efficiently! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

* **Complain** - 1 if customer complained in the last 2 years
* **DtCustomer** - date of customer’s enrolment with the company
* **Education** - customer’s level of education
* **Marital** - customer’s marital status
* **Kidhome** - number of small children in customer’s household
* **Teenhome** - number of teenagers in customer’s household
* **ID** - Customer's id
* **Income** - customer’s yearly household income
* **NumDealsPurchases** - number of purchases made with discount
* **NumCatalogPurchases** - number of purchases made using catalogue
* **NumStorePurchases** - number of purchases made directly in stores
* **NumWebPurchases** - number of purchases made through company’s web site
* **NumWebVisitsMonth** - number of visits to company’s web site in the last month
* **Recency** - number of days since the last purchase
* **Year_Birth** - customer's year of birth

**Import pandas as pd.**

**Read Salaries.csv as a dataframe called sal.**

*   csv: comma-separated values

**Check the head of the DataFrame.**

*.head()*
*   Returns the first n rows for the object based on position. 
*   It is useful for quickly testing if your object has the right type of data in it.
*   For negative values of n, this function returns all rows except the last n rows, equivalent to df[:-n].

**Use the .info() method to find out how many entries there are.**

*.info()*
*   Print a concise summary of a DataFrame.
*   prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.

**What is the average amount of Income?**

*.mean()*
*   Returns the mean of the values for the requested axis.

**What is the highest amount of Income in the dataset ?**

*.max()*
*   Returns the maximum of the values for the requested axis.
*   If you want the index of the maximum, use idxmax. This is the equivalent of the numpy.ndarray method argmax.

**What is the marital status of the customer with the ID of 5544?**

**How much does the customer with the ID 5544 make?**

**What are the IDs of the youngest customers?**

**What is the ID of the oldest customer? Do you notice something strange about the customer?**

**What was the average (mean) Income of all customers by education?**

*.groupby()*
*   Group Series using a mapper or by a Series of columns.
*   A groupby operation involves some combination of splitting the object, applying a function, and combining the results.
*   This can be used to group large amounts of data and compute operations on these groups.

 **How many unique birth years are there?**

*.unique()*
*   Return unique values of Series object.
*   Uniques are returned in order of appearance. Hash table-based unique, therefore does NOT sort.

*.nunique()*
*   Return number of unique elements in the object.
*   Excludes NA values by default.

**What are the top 5 most common years of birth?**

*.value_counts()*
*   Returns a Series containing counts of unique values.
*   The resulting object will be in descending order so that the first element is the most frequently-occurring element. Excludes NA values by default.

**How many customers have a unique year of birth? (eg. They are the only customers from their respective birth year)**

**How many customers enrolled as a member in May? (This is pretty tricky)**

*.apply()*
*   Invoke function on values of Series.
*   Can be ufunc (a NumPy function that applies to the entire Series) or a Python function that only works on single values.

*Lambda*
*   A lambda function can take any number of arguments, but can only have **one expression**.
*   Syntax
> lambda arguments : expression
*   Example

    x = lambda a : a + 20 

    print(x(5))

    Output: 25

*(BONUS)* **Is there a correlation between Income and Amount of Offsprings?**